### ISSUE TITLE
Don't store OAuth API Keys in code 

### ISSUE THREAD

**Issue by robbyoconnor** [hackathons-com/hackathons.com#2]
I would recommend strongly that you not store API keys in code -- decommission the API keys already published and regenerate new ones. 

Use either [dotenv](https://github.com/bkeepers/dotenv) or [figaro](https://github.com/laserlemon/figaro) -- just **DO NOT** store API keys in code -- not only is it not good, it's **REALLLLLLLY** bad. 

Currently omniauth code stores the API keys in the code -- and this is **BAD** -- If you used EC2 -- you'd have so many charges...

**Comment by rodrigoargumedo** [comment]
This is the old version of the repo see https://github.com/hackathons-com/Rails-MongoDB-Devise-test/issues/1
